### ISSUE TITLE
Installation File requires additional UPLOAD and MODIFICATION Values

### ISSUE THREAD

**Issue by IP-CAM** [pekka2/Opencart-1.5.6.5-Edge#1]
as I have added (but not yet tested) in this **cli_install.php** file:
[cli_install.php.txt](https://github.com/pekka2/Opencart-1.5.6.5-Edge/files/1167580/cli_install.php.txt)

**Comment by pekka2** [comment]
What is the purpose of this file? It is also Opencart 1.5.6.4 versions, I is not tested it. Is mean that file?
