### ISSUE TITLE
Make this OpenCart Version capable to work with PHP-7.x

### ISSUE THREAD

**Issue by IP-CAM** [pekka2/Opencart-1.5.6.5-Edge#10]
Download this system/library/encryption_php.txt file, rename it to encryption.php, and replace the existing encryption.php file to enable this Version to further function with php v.7.x:
http://www.ipc.li/os/encryption_php.txt

**Comment by condor2** [comment]
I made some small changes
https://github.com/pekka2/Opencart-1.5.6.5-Edge/pulls

**Comment by IP-CAM** [comment]
Fine Job, it's ready now for a revival !
