### ISSUE TITLE
PHP 7.1.7 error

### ISSUE THREAD

**Issue by rrhussain** [pekka2/Opencart-1.5.6.5-Edge#2]
Hi,
I am trying to install this version with php 7.1.7 I am still getting error MYSQL extension off. I read on lots of forum that version is compatible with php7.

Any help will be appreciate.

Thanks

**Comment by IP-CAM** [comment]
OpenCart 1.5.6.5 cannot be used with PHP 7.1 , but only up to PHP 7.0.2x !
And it requires an updated install-routine, to be installable the regular way as well with PHP 7.0.2x,
and you can find the modified installation Files here:
https://forum.opencart.com/viewtopic.php?f=199&t=187165&p=684259#p684259
Ernie

**Comment by pekka2** [comment]
@rrhussain 
Are you downloaded latest version? I am fixed this:
https://github.com/pekka2/Opencart-1.5.6.5-Edge/commit/79be2b3d1061bed02cfd24029eb7544abf03c205
