### ISSUE TITLE
Minor difference found in account / success.tpl file

### ISSUE THREAD

**Issue by IP-CAM** [pekka2/Opencart-1.5.6.5-Edge#3]
hi, wich one of those lines would be the correct one to use ?
Ernie
---
\catalog\controller\account\success.php Line 35:
---
Default OC v.1.5.6.5_rc:
$this->data['text_message'] = sprintf($this->language->get('text_message'), $this->url->link('information/contact'));
OC 1.5.6.5 Edge:
$this->data['text_message'] = sprintf($this->language->get('text_message'), $this->url->link('information/contact'),'');

**Comment by pekka2** [comment]
Latter line
