### ISSUE TITLE
Make this Version work up to php v.7.2.0

### ISSUE THREAD

**Issue by IP-CAM** [pekka2/Opencart-1.5.6.5-Edge#6]
```
To make OC work with PHP v.7.2.x as well!
in:
catalog/model/module/module.php (Line 16)
change:
```
`if (count($array[0]) > 0 && is_array($array)) {`
`to:`
`if (is_array($array) && count($array[0]) > 0) {`
```
Ernie
```
[https://forum.opencart.com/viewtopic.php?f=179&t=205523&p=728778#p728778](https://forum.opencart.com/viewtopic.php?f=179&t=205523&p=728778#p728778)

**Comment by pekka2** [comment]
Thanks ;)
